# Copyright (c) 2025, AgriTheory and contributors
# For license information, please see license.txt

import os
import secrets

import click
import frappe
from frappe.commands import get_site, pass_context


@click.command("migrate-passwords-to-vault")
@click.option("--dry-run", is_flag=True, help="Show what would be migrated without making changes")
@click.option("--skip-backup", is_flag=True, help="Skip creating a backup (not recommended)")
@pass_context
def migrate_passwords_to_vault(context, dry_run=False, skip_backup=False):
	"""Migrate existing passwords from __Auth table to OpenBao."""
	site = get_site(context)
	frappe.init(site=site)
	frappe.connect()

	from frappe_vault.install import migrate_passwords_to_vault as do_migrate

	try:
		do_migrate(dry_run=dry_run, skip_backup=skip_backup)
	finally:
		frappe.destroy()


@click.command("restore-auth-backup")
@click.argument("backup_file")
@pass_context
def restore_auth_backup(context, backup_file):
	"""Restore __Auth table from a backup file created during migration."""
	site = get_site(context)
	frappe.init(site=site)
	frappe.connect()

	from frappe_vault.install import restore_auth_backup as do_restore

	try:
		do_restore(backup_file)
	finally:
		frappe.destroy()


@click.command("cleanup-migrated-passwords")
@click.option("--confirm", is_flag=True, help="Actually delete the migrated passwords from __Auth")
@pass_context
def cleanup_migrated_passwords(context, confirm=False):
	"""Remove passwords from __Auth that have been migrated to OpenBao."""
	site = get_site(context)
	frappe.init(site=site)
	frappe.connect()

	from frappe_vault.install import cleanup_migrated_passwords as do_cleanup

	try:
		do_cleanup(confirm=confirm)
	finally:
		frappe.destroy()


@click.command("vault-status")
@pass_context
def vault_status(context):
	"""Check OpenBao connectivity and configuration status."""
	site = get_site(context)
	frappe.init(site=site)
	frappe.connect()

	try:
		print(f"Site: {site}")
		print(f"enable_vault_secrets: {frappe.conf.get('enable_vault_secrets', False)}")
		print(f"enable_vault_user_passwords: {frappe.conf.get('enable_vault_user_passwords', False)}")
		print(f"vault_url: {frappe.conf.get('vault_url', 'not set')}")
		print(f"vault_proxy_enabled: {frappe.conf.get('vault_proxy_enabled', False)}")

		from frappe_vault.vault_client import get_vault_client

		try:
			client = get_vault_client()
			available = client.is_available()
			print(f"\nOpenBao Status: {'✓ Connected' if available else '✗ Not Available'}")
			if available:
				health = client.check_health()
				print(f"  Initialized: {health.get('initialized', 'unknown')}")
				print(f"  Sealed: {health.get('sealed', 'unknown')}")
		except Exception as e:
			print(f"\nOpenBao Status: ✗ Error - {e}")

		# Count passwords in __Auth
		Auth = frappe.qb.Table("__Auth")
		auth_count = (
			frappe.qb.from_(Auth)
			.select(frappe.qb.functions.Count("*"))
			.where(Auth.password.isnotnull())
			.run()
		)[0][0]
		print(f"\nPasswords in __Auth table: {auth_count}")

	finally:
		frappe.destroy()


def _get_bench_path():
	"""Get the bench path, works both inside and outside frappe context."""
	try:
		from frappe.utils import get_bench_path

		return get_bench_path()
	except Exception:
		# Fallback: walk up from current directory looking for sites folder
		cwd = os.getcwd()
		while cwd != "/":
			if os.path.isdir(os.path.join(cwd, "sites")):
				return cwd
			cwd = os.path.dirname(cwd)
		return os.getcwd()


def _write_file_secure(path: str, content: str, mode: int = 0o600) -> None:
	"""Write a file with secure permissions."""
	# Create parent directory if needed
	parent_dir = os.path.dirname(path)
	if parent_dir and not os.path.exists(parent_dir):
		os.makedirs(parent_dir, mode=0o755)

	# Write with restrictive permissions
	fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, mode)
	try:
		os.write(fd, content.encode())
	finally:
		os.close(fd)


def _generate_openbao_config(seal_key_path: str, data_path: str) -> str:
	"""Generate OpenBao configuration file content."""
	return f"""# OpenBao configuration for Frappe Vault
# Generated by: bench generate-seal-key --init-config
# Documentation: https://openbao.org/docs/configuration

ui = true

storage "file" {{
  path = "{data_path}"
}}

listener "tcp" {{
  address     = "127.0.0.1:8200"
  tls_disable = true  # TLS handled by nginx reverse proxy
}}

# Static seal for auto-unseal on restart
# This allows OpenBao to unseal automatically after bench restart
seal "static" {{
  current_key_id = "frappe-vault-1"
  current_key = "file://{seal_key_path}"
}}

api_addr = "http://127.0.0.1:8200"
"""


@click.command("generate-seal-key")
@click.option(
	"--output", "-o", type=click.Path(), help="Write key to file with secure permissions (0600)"
)
@click.option(
	"--init-config",
	is_flag=True,
	help="Create full OpenBao config in bench config directory (config/openbao.hcl)",
)
def generate_seal_key(output=None, init_config=False):
	"""Generate a seal key for OpenBao static seal auto-unseal.

	This command generates a cryptographically secure 32-byte (256-bit) key
	suitable for use with OpenBao's static seal configuration. The key enables
	OpenBao to automatically unseal on restart without manual intervention.

	Example usage:

	\b
	    # Just generate a key and show configuration options
	    bench generate-seal-key

	\b
	    # Create full OpenBao config in bench directory (recommended)
	    bench generate-seal-key --init-config

	\b
	    # Write key to a specific file
	    bench generate-seal-key --output /path/to/seal.key
	"""
	# Generate a 32-byte (256-bit) key as 64 hex characters
	key = secrets.token_hex(32)

	if init_config:
		# Create full OpenBao config in bench config directory
		bench_path = _get_bench_path()
		config_dir = os.path.join(bench_path, "config")
		data_dir = os.path.join(config_dir, "openbao-data")

		config_path = os.path.join(config_dir, "openbao.hcl")
		seal_key_path = os.path.join(config_dir, "openbao-seal.key")

		try:
			# Create data directory
			os.makedirs(data_dir, mode=0o700, exist_ok=True)

			# Write seal key
			_write_file_secure(seal_key_path, key + "\n", mode=0o600)

			# Write config file
			config_content = _generate_openbao_config(seal_key_path, data_dir)
			_write_file_secure(config_path, config_content, mode=0o644)

			print("OpenBao configuration created successfully!")
			print()
			print("Files created:")
			print(f"  Config:   {config_path}")
			print(f"  Seal key: {seal_key_path}")
			print(f"  Data dir: {data_dir}")
			print()
			print("=" * 60)
			print("NEXT STEPS")
			print("=" * 60)
			print()
			print("1. Add OpenBao to supervisor config.")
			print("   Create /etc/supervisor/conf.d/openbao.conf:")
			print()
			print("   [program:openbao]")
			print(f"   command=/usr/bin/bao server -config={config_path}")
			print("   autostart=true")
			print("   autorestart=true")
			print(f"   directory={bench_path}")
			print("   stdout_logfile=/var/log/openbao/openbao.log")
			print("   stderr_logfile=/var/log/openbao/openbao-error.log")
			print()
			print("2. Create log directory and reload supervisor:")
			print()
			print("   sudo mkdir -p /var/log/openbao")
			print("   sudo supervisorctl reread")
			print("   sudo supervisorctl update")
			print()
			print("3. Initialize OpenBao (first time only):")
			print()
			print("   export BAO_ADDR='http://127.0.0.1:8200'")
			print("   bao operator init -recovery-shares=1 -recovery-threshold=1")
			print()
			print("   Save the recovery key and root token securely!")
			print()
			print("4. Enable the secrets engine and create policy:")
			print()
			print("   export BAO_TOKEN='<root-token-from-init>'")
			print("   bao secrets enable -path=secret kv-v2")
			print()
			print("=" * 60)

		except PermissionError as e:
			print(f"Error: Permission denied - {e}")
			raise SystemExit(1)
		except Exception as e:
			print(f"Error creating config: {e}")
			raise SystemExit(1)

	elif output:
		# Write to file with secure permissions
		try:
			_write_file_secure(output, key + "\n", mode=0o600)

			print(f"Seal key written to: {output}")
			print("File permissions: 0600 (owner read/write only)")
			print()
			print("Add to your OpenBao config.hcl:")
			print()
			print('seal "static" {')
			print('  current_key_id = "frappe-vault-1"')
			print(f'  current_key = "file://{os.path.abspath(output)}"')
			print("}")

		except PermissionError:
			print(f"Error: Permission denied writing to {output}")
			print("Try running with sudo or choose a different path.")
			raise SystemExit(1)
		except Exception as e:
			print(f"Error writing key file: {e}")
			raise SystemExit(1)
	else:
		# Output to stdout with configuration examples
		bench_path = _get_bench_path()

		print("Generated OpenBao Static Seal Key")
		print("=" * 60)
		print()
		print(f"Key: {key}")
		print()
		print("=" * 60)
		print("RECOMMENDED: Use --init-config to auto-create config files")
		print("=" * 60)
		print()
		print("  bench generate-seal-key --init-config")
		print()
		print(f"This will create OpenBao config in: {bench_path}/config/")
		print()
		print("=" * 60)
		print("MANUAL CONFIGURATION OPTIONS")
		print("=" * 60)
		print()
		print("Option A: Environment Variable")
		print("-" * 60)
		print()
		print("1. Add to OpenBao config.hcl:")
		print()
		print('   seal "static" {')
		print('     current_key_id = "frappe-vault-1"')
		print('     current_key = "env://BAO_SEAL_KEY"')
		print("   }")
		print()
		print("2. Add to supervisor config:")
		print()
		print("   [program:openbao]")
		print("   command=/usr/bin/bao server -config=/path/to/config.hcl")
		print(f'   environment=BAO_SEAL_KEY="{key}"')
		print()
		print()
		print("Option B: File-Based")
		print("-" * 60)
		print()
		print("1. Create the key file:")
		print()
		print(f'   echo "{key}" > {bench_path}/config/openbao-seal.key')
		print(f"   chmod 600 {bench_path}/config/openbao-seal.key")
		print()
		print("2. Add to OpenBao config.hcl:")
		print()
		print('   seal "static" {')
		print('     current_key_id = "frappe-vault-1"')
		print(f'     current_key = "file://{bench_path}/config/openbao-seal.key"')
		print("   }")
		print()
		print("=" * 60)
		print("IMPORTANT: Store this key securely! Anyone with access to")
		print("this key can unseal your OpenBao instance.")
		print("=" * 60)


commands = [
	migrate_passwords_to_vault,
	cleanup_migrated_passwords,
	restore_auth_backup,
	vault_status,
	generate_seal_key,
]
